services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "@cl4r4n3t!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./create-database.sql:/tmp/create-database.sql
      - ./create-database-tests.sql:/tmp/create-database-tests.sql
      - ./init-database.sh:/tmp/init-database.sh
    command: /bin/bash ./tmp/init-database.sh